name: bdaya_custom_splash
description: Custom splash used at bdaya-dev
version: 0.0.2
author: Bdaya Development
homepage: bdaya-dev.com

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  shimmer: ^2.0.0-nullsafety.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
